apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-service.fullname" . }}-config-map
data:
  database_server_address: {{ .Values.databaseServerAddress }}
  zipkin_server_address: {{ .Values.zipkinServerAddress }}
  kafka_server_address: {{ .Values.kafkaServerAddress }}
  config_service_url: {{ .Values.configServiceUrl }}
  change_password_url: {{ .Values.changePasswordUrl }}