apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camera-service.fullname" . }}-config-map
data:
  database_server_address: {{ .Values.databaseServerAddress }}
  zipkin_server_address: {{ .Values.zipkinServerAddress }}
  config_service_url: {{ .Values.configServiceUrl }}
  check_camera_url: {{ .Values.checkCameraUrl }}