apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config-map
data:
  zipkin_server_address: {{ .Values.zipkinServerAddress }}
  config_service_url: {{ .Values.configServiceUrl }}