apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-service.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    {{ include "gateway-service.labels" . | nindent 4}}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
