server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.account

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: 123456
    username: tung
    url: jdbc:mysql://localhost:3306/account_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
system:
  supperAdmin:
    fullname: admin
    username: admin
    email: admin@gmail.com
    password: Admin@123
    organization: Comit
frontend:
  server: http://localhost:3005/authentication/change-password
app:
  jwtExpirationInMs: 2059200000
  jwtSecret: comit_admin
