server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.organization

spring:
  datasource:
    username: tung
    url: jdbc:mysql://localhost:3306/organization_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
system:
  supperAdmin:
    organization: Comit