apiVersion: v1
kind: Service
metadata:
  name: {{ include "comit-admin.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    {{ include "comit-admin.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
