app: k8s-metadata-service
image: thanhtungtvg95/metadata-service:latest
replicas: 1
port: 8091
databaseServerAddress: localhost:3306
zipkinServerAddress: http://localhost:9411
configServiceUrl: http://location:8088
storageHost: localhost
storageFolder: /path/to/folder
username: ZGVtbw==
password: ZGVtbw==