apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-cm
data:
  zipkin_server_address: http://10.10.2.202:9411
  kafka_server_address: 10.10.2.202:29092
  config_service_url: http://10.10.2.202:8088

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: k8s-mail-service
  ports:
    - port: 80
      targetPort: 8085

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mail-service
  labels:
    app: k8s-mail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mail-service
  template:
    metadata:
      labels:
        app: k8s-mail-service
    spec:
      containers:
        - name: mail-service
          image: thanhtungtvg95/mail-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: mail-cm
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: mail-cm
            - name: KAFKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: kafka_server_address
                  name: mail-cm
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mail_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: mail_password

