apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-cm
data:
  database_server_address: 10.10.2.202:3306
  zipkin_server_address: http://10.10.2.202:9411
  config_service_url: http://10.10.2.202:8088

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-metadata-service
  labels:
    app: k8s-metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-metadata-service
  template:
    metadata:
      labels:
        app: k8s-metadata-service
    spec:
      containers:
        - name: metadata-service
          image: thanhtungtvg95/metadata-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: metadata-cm
            - name: DATABASE_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: database_server_address
                  name: metadata-cm
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: metadata-cm
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
