apiVersion: v1
kind: ConfigMap
metadata:
  name: camera-cm
data:
  database_server_address: 10.10.2.202:3306
  zipkin_server_address: http://10.10.2.202:9411
  check_camera_url: http://10.10.2.116:5678/camera/check_cameras
  config_service_url: http://10.10.2.202:8088

---

apiVersion: v1
kind: Service
metadata:
  name: camera-service
spec:
  selector:
    app: k8s-camera-service
  ports:
    - port: 80
      targetPort: 8083

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-camera-service
  labels:
    app: k8s-camera-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-camera-service
  template:
    metadata:
      labels:
        app: k8s-camera-service
    spec:
      containers:
        - name: camera-service
          image: thanhtungtvg95/camera-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: camera-cm
            - name: DATABASE_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: database_server_address
                  name: camera-cm
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: camera-cm
            - name: CHECK_CAMERA_URL
              valueFrom:
                configMapKeyRef:
                  key: check_camera_url
                  name: camera-cm
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password