apiVersion: v1
kind: Service
metadata:
  name: time-keeping-service
spec:
  selector:
    app: k8s-time-keeping-service
  ports:
    - port: 80
      targetPort: 8089

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-time-keeping-service
  labels:
    app: k8s-time-keeping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-time-keeping-service
  template:
    metadata:
      labels:
        app: k8s-time-keeping-service
    spec:
      containers:
        - name: time-keeping-service
          image: thanhtungtvg95/time-keeping-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: config-map
            - name: DATABASE_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: database_server_address
                  name: config-map
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: config-map
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
