apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
data:
  zipkin_server_address: http://10.10.2.202:9411
  config_service_url: http://10.10.2.202:8088

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-gateway-service
  ports:
    - port: 80
      targetPort: 8070
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-gateway-service
  labels:
    app: k8s-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-gateway-service
  template:
    metadata:
      labels:
        app: k8s-gateway-service
    spec:
      containers:
        - name: gateway-service
          image: thanhtungtvg95/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: gateway-cm
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: gateway-cm