apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-cm
data:
  storage_host: localhost
  storage_folder: /part/to/folder

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-metadata-service
  labels:
    app: k8s-metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-metadata-service
  template:
    metadata:
      labels:
        app: k8s-metadata-service
    spec:
      containers:
        - name: metadata-service
          image: thanhtungtvg95/metadata-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: config-map
            - name: DATABASE_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: database_server_address
                  name: config-map
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: config-map
            - name: STORAGE_HOST
              valueFrom:
                configMapKeyRef:
                  key: storage_host
                  name: metadata-cm
            - name: STORAGE_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: storage_folder
                  name: metadata-cm
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
