apiVersion: v1
kind: ConfigMap
metadata:
  name: ott-service-config-map
data:
  MODE: production
  PORT: 3002
  # Kafka
  KAFKA_HOST: localhost
  KAFKA_PORT: 29092
  KAFKA_CLIENT_ID: demo
  KAFKA_GROUP_ID: demo
  KAFKA_TIME_KEEPING_NOTIFICATION_OTT_TOPIC: demo_6
  KAFKA_AREA_RESTRICTION_OTT_TOPIC: demo_7
  # Database
  DB_HOST: localhost
  DB_DBNAME: demo
  DB_USERNAME: ZGVtbw==
  DB_PASSWORD: ZGVtbw==
  # Telegram
  TOKEN_BOT_API: demo
  TELEGRAM_BOT_LINK: demo
  #API
  BASE_URL: http://192.168.6.114:8070