apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-server-config-map
data:
  MODE: production
  PORT: 3000
  HOST: localhost
  # Kafka
  KAFKA_HOST: localhost
  KAFKA_PORT: 29092
  KAFKA_CLIENT_ID: demo
  KAFKA_GROUP_ID: demo
  KAFKA_STREAM_CAMERA_TOPIC: demo_1
  KAFKA_TIME_KEEPING_TOPIC: demo_2
  KAFKA_AREA_RESTRICTION_TOPIC: demo_3
  KAFKA_TIME_KEEPING_NOTIFICATION_MAIL_TOPIC: demo_4
  KAFKA_AREA_RESTRICTION_MAIL_TOPIC: demo_5
  KAFKA_TIME_KEEPING_NOTIFICATION_OTT_TOPIC: demo_6
  KAFKA_AREA_RESTRICTION_OTT_TOPIC: demo_7
  # Socket
  WEB_SOCKET_IN_OUT_PORT: 4005
  #Redis
  REDIS_PORT: 
  REDIS_HOST: 
  REDIS_USERNAME: 
  REDIS_PASSWORD: 
  REDIS_EXPIRE_TIME:
  #API
  BASE_URL: http://192.168.6.114:8070