apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account-service.fullname" . }}-credentials
data:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  sa_full_name: {{ .Values.saFullName }}
  sa_username: {{ .Values.saUsername }}
  sa_email: {{ .Values.saEmail }}
  sa_password: {{ .Values.saPassword }}
  sa_organization: {{ .Values.saOrganization }}
  jwt_secret: {{ .Values.jwtSecret }}