apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "employee-service.fullname" . }}-config-map
data:
  database_server_address: {{ .Values.databaseServerAddress }}
  zipkin_server_address: {{ .Values.zipkinServerAddress }}
  kafka_server_address: {{ .Values.kafkaServerAddress }}
  config_service_url: {{ .Values.configServiceUrl }}
  action_employee_image_url: {{ .Values.actionEmployeeImageUrl}}