app: k8s-time-keeping-service
image: thanhtungtvg95/time-keeping-service:latest
replicas: 1
port: 8089
databaseServerAddress: localhost:3306
zipkinServerAddress: http://localhost:9411
configServiceUrl: http://location:8088
username: ZGVtbw==
password: ZGVtbw==