apiVersion: v1
kind: Service
metadata:
  name: {{ include "organization-service.fullname" . }}
spec:
  selector:
    {{- include "organization-service.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}