apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "discovery-service.name" . }}
  labels:
    {{- include "discovery-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "discovery-service.fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "discovery-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "discovery-service.labels" . | nindent 8}}
    spec:
      containers:
        - name: {{ include "discovery-service.fullname" . }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: config_service_url
                  name: {{ include "discovery-service.fullname" . }}-config-map
            - name: DISCOVERY_SERVICE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: discovery_service_address
                  name: {{ include "discovery-service.fullname" . }}-config-map
            - name: ZIPKIN_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: zipkin_server_address
                  name: {{ include "discovery-service.fullname" . }}-config-map

