apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata-service.fullname" . }}-config-map
data:
  database_server_address: {{ .Values.databaseServerAddress }}
  zipkin_server_address: {{ .Values.zipkinServerAddress }}
  config_service_url: {{ .Values.configServiceUrl }}
  storage_host: {{ .Values.storageHost }}
  storage_folder: {{ .Values.storageFolder }}