apiVersion: v1
kind: Service
metadata:
  name: {{ include "area-restriction-service.fullname" . }}
spec:
  selector:
    {{- include "area-restriction-service.labels" . | nindent 4}}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}